{
 "title": "NodeOperators",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "nos_name_var",
    "label": "Node Operator",
    "query": {
     "query": "query_result(catalist_validators_monitoring_user_validators)"
    }
   },
   { "name": "show_dvts_var", "label": "Show related clusters", "query": "Yes : 1, No : -1" },
   {
    "name": "epoch_number_var",
    "label": "Epoch number",
    "query": {
     "query": "query_result(catalist_validators_monitoring_epoch_number)"
    }
   },
   {
    "name": "sync_participation_distance_var",
    "label": "Sync participation distance down from chain avg",
    "query": {
     "query": "query_result(catalist_validators_monitoring_sync_participation_distance_down_from_chain_avg)"
    }
   },
   { "name": "limit", "label": "Row limit", "query": "100" },
   {
    "name": "att_epochs_var",
    "query": {
     "query": "label_values(catalist_validators_monitoring_validator_count_miss_attestation_last_n_epoch, epoch_interval)"
    }
   },
   {
    "name": "sync_epochs_var",
    "query": {
     "query": "label_values(catalist_validators_monitoring_validator_count_with_sync_participation_less_avg_last_n_epoch, epoch_interval)"
    }
   },
   {
    "name": "chain_sync_avg_participation",
    "label": "Chain sync participation avg",
    "query": {
     "query": "query_result(catalist_validators_monitoring_chain_sync_participation_avg_percent)"
    }
   },
   {
    "name": "epochs_range",
    "label": "Epochs range",
    "query": {
     "query": "query_result(sum_over_time((changes(sum(catalist_validators_monitoring_epoch_number)[25s:]) > 0)[$__range:]))"
    }
   },
   {
    "name": "nos_global_index_var",
    "label": "Node Operator Global Index",
    "query": {
     "query": "query_result(label_join(catalist_validators_monitoring_user_validators{nos_name='${nos_name_var}'}, \"nos_global_index\", \";\", \"nos_module_id\", \"nos_id\"))"
    }
   },
   {
    "name": "dvt_nos_global_indexes_var",
    "label": "Node Operator Global Index",
    "query": {
     "query": "query_result(operators_indexes_map{main_global_index='${nos_global_index_var}'} == ${show_dvts_var})"
    }
   },
   {
    "name": "mapped_nos_names_var",
    "label": "Node Operator",
    "query": {
     "query": "query_result(catalist_validators_monitoring_user_operators_identifies{nos_global_index=~'${nos_global_index_var}|${dvt_nos_global_indexes_var}'})"
    }
   }
  ]
 },
 "panels": [
  { "title": "App", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Data actuality",
   "type": "stat",
   "description": "Difference between `Now` and timestamp of last slot of processed epoch ",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(catalist_validators_monitoring_data_actuality)"
    }
   ]
  },
  {
   "title": "Data actuality x Epoch",
   "type": "timeseries",
   "description": "Difference between `Now` and timestamp of last slot of processed epoch ",
   "gridPos": { "h": 4, "w": 7, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(catalist_validators_monitoring_data_actuality)",
     "legendFormat": "Data actuality"
    },
    {
     "expr": "catalist_validators_monitoring_epoch_number",
     "legendFormat": "Epoch"
    }
   ]
  },
  {
   "title": "Node operator",
   "type": "stat",
   "gridPos": { "h": 4, "w": 10, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (nos_name) (catalist_validators_monitoring_user_validators{nos_name=~\"${mapped_nos_names_var}\"})",
     "legendFormat": "🏖️  {{nos_name}}"
    }
   ]
  },
  {
   "title": "Unmonitored keys",
   "type": "stat",
   "description": "Number of unmonitored (stuck) keys that are defined manually. Such keys will not be taken into account when calculating validator metrics and alerts",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(catalist_validators_monitoring_user_validators{status=\"stuck\",nos_name=\"${nos_name_var}\"})"
    }
   ]
  },
  {
   "title": "Epoch",
   "type": "stat",
   "description": "Last processed for a specified time period",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(catalist_validators_monitoring_epoch_number)"
    }
   ]
  },
  { "title": "🏠 General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Ongoing validators",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(catalist_validators_monitoring_user_validators{status=\"ongoing\",nos_name=~\"${mapped_nos_names_var}\"})",
     "legendFormat": "{{owner}}"
    }
   ]
  },
  {
   "title": "Pending validators",
   "type": "stat",
   "description": "Alias for `pending_queued` and `pending_initialized` statuses",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(catalist_validators_monitoring_user_validators{status=\"pending\",nos_name=~\"${mapped_nos_names_var}\"})",
     "legendFormat": "{{owner}}"
    }
   ]
  },
  {
   "title": "Full withdrawal pending",
   "type": "stat",
   "description": "Alias for `active_exiting`, `exited_unslashed`, `exited_slashed` and `withdrawal_possible` statuses",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(catalist_validators_monitoring_user_validators{nos_name=~\"${mapped_nos_names_var}\",status=\"withdrawal_pending\"})",
     "legendFormat": "{{owner}}"
    }
   ]
  },
  {
   "title": "Full withdrawn",
   "type": "stat",
   "description": "Alias for `withdrawal_done`, and `withdrawal_possible` statuses. `withdrawal_possible` is considered fully withdrawn when the validator balance is `0`.",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(catalist_validators_monitoring_user_validators{nos_name=~\"${mapped_nos_names_var}\",status=\"withdrawal_done\"})",
     "legendFormat": "{{owner}}"
    }
   ]
  },
  {
   "title": "Slashed validators",
   "type": "stat",
   "description": "Alias for `active_slashed`, `exited_slashed` or any validator status with `slashed = true` in state",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(catalist_validators_monitoring_user_validators{status=\"slashed\",nos_name=~\"${mapped_nos_names_var}\"})",
     "legendFormat": "{{owner}}"
    }
   ]
  },
  {
   "title": "Ongoing validators share",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(catalist_validators_monitoring_user_validators{status=\"ongoing\",nos_name=~\"${mapped_nos_names_var}\"})",
     "legendFormat": "Selected"
    },
    {
     "expr": "sum(catalist_validators_monitoring_user_validators{status=\"ongoing\",nos_name!~\"${mapped_nos_names_var}\"})",
     "legendFormat": "User (other)"
    }
   ]
  },
  {
   "title": "Pending validators share",
   "type": "piechart",
   "description": "Alias for `pending_queued` and `pending_initialized` statuses",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(catalist_validators_monitoring_user_validators{status=\"pending\",nos_name=~\"${mapped_nos_names_var}\"})",
     "legendFormat": "Selected"
    },
    {
     "expr": "sum(catalist_validators_monitoring_user_validators{status=\"pending\",nos_name!~\"${mapped_nos_names_var}\"})",
     "legendFormat": "User (other)"
    }
   ]
  },
  {
   "title": "Full withdrawal pending",
   "type": "piechart",
   "description": "Alias for `active_exiting`, `exited_unslashed`, `exited_slashed` and `withdrawal_possible` statuses",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(catalist_validators_monitoring_user_validators{status=\"withdrawal_pending\",nos_name=~\"${mapped_nos_names_var}\"})",
     "legendFormat": "Selected"
    },
    {
     "expr": "sum(catalist_validators_monitoring_user_validators{status=\"withdrawal_pending\",nos_name!~\"${mapped_nos_names_var}\"})",
     "legendFormat": "User (other)"
    }
   ]
  },
  {
   "title": "Full withdrawn",
   "type": "piechart",
   "description": "Alias for `withdrawal_done`, and `withdrawal_possible` statuses. `withdrawal_possible` is considered fully withdrawn when the validator balance is `0`.",
   "gridPos": { "h": 7, "w": 5, "x": 15, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(catalist_validators_monitoring_user_validators{nos_name=~\"${nos_name_var}\",status=\"withdrawal_done\"})",
     "legendFormat": "Selected"
    },
    {
     "expr": "sum(catalist_validators_monitoring_user_validators{nos_name!~\"${mapped_nos_names_var}\",status=\"withdrawal_done\"})",
     "legendFormat": "User (other)"
    }
   ]
  },
  {
   "title": "Slashed validators share",
   "type": "piechart",
   "description": "Alias for `active_slashed`, `exited_slashed` or any validator status with `slashed = true` in state",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(catalist_validators_monitoring_user_validators{status=\"slashed\",nos_name=~\"${nos_name_var}\"})",
     "legendFormat": "Selected"
    },
    {
     "expr": "sum(catalist_validators_monitoring_user_validators{status=\"slashed\",nos_name!~\"${mapped_nos_names_var}\"})",
     "legendFormat": "User (other)"
    }
   ]
  },
  {
   "title": "Status progress",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 13, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum by (status) (catalist_validators_monitoring_user_validators{status=~\"ongoing|pending|withdrawal_pending|withdrawal_done\",nos_name=~\"${mapped_nos_names_var}\"}) AND ON() changes(catalist_validators_monitoring_epoch_number[$__rate_interval]) > 0",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "On exit validators",
   "type": "table",
   "gridPos": { "h": 10, "w": 11, "x": 13, "y": 16 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    if('${dvt_nos_global_indexes_var}' != '', val_nos_name, NULL) as Operator,\n    val_id as Validator,\n    val_status as Status,\n    val_balance / pow(10,9) as Balance\nFROM\n    validators_summary\nWHERE\n    CONCAT(toString(val_nos_module_id), ';', toString(val_nos_id))\n      IN arrayConcat(['${nos_global_index_var}'], splitByChar('|','${dvt_nos_global_indexes_var}')) AND\n    epoch = ${epoch_number_var} AND\n    (val_status in ['active_exiting','exited_unslashed', 'exited_slashed'] or val_status == 'withdrawal_possible' and val_balance != 0)\nORDER BY val_id, val_balance\nLIMIT 1 by val_id",
     "rawQuery": "SELECT\n    if('2;0|2;1' != '', val_nos_name, NULL) as Operator,\n    val_id as Validator,\n    val_status as Status,\n    val_balance / pow(10,9) as Balance\nFROM\n    validators_summary\nWHERE\n    CONCAT(toString(val_nos_module_id), ';', toString(val_nos_id))\n      IN arrayConcat(['1;0'], splitByChar('|','2;0|2;1')) AND\n    epoch = 222117 AND\n    (val_status in ['active_exiting','exited_unslashed', 'exited_slashed'] or val_status == 'withdrawal_possible' and val_balance != 0)\nORDER BY val_id, val_balance\nLIMIT 1 by val_id",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Total withdrawals count by type",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 13, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum by (type) (catalist_validators_monitoring_operator_withdrawals_count{nos_name=~\"${mapped_nos_names_var}\"}) AND ON() changes(catalist_validators_monitoring_epoch_number[$__rate_interval]) > 0",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "💔 Alerting only (at incident time range)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 }
  },
  {
   "title": "Negative balance delta",
   "type": "table",
   "description": "Delta: current slot - 192 slot",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 27 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n  if('${dvt_nos_global_indexes_var}' != '', current.val_nos_name, NULL) as Operator,\n  current.val_balance - previous.val_balance + ifNull(withdrawals.withdrawn, 0) AS GWei,\n  current.val_id as Validator\nFROM \n  (\n    SELECT val_balance, val_id, val_nos_id, val_slashed, val_nos_name\n    FROM validators_summary \n    WHERE \n      val_status in ['active_ongoing', 'active_exiting', 'active_slashed', 'pending_initialized'] AND\n      CONCAT(toString(val_nos_module_id), ';', toString(val_nos_id))\n        IN arrayConcat(['${nos_global_index_var}'], splitByChar('|','${dvt_nos_global_indexes_var}')) AND\n      val_stuck = 0 AND\n      epoch = ${epoch_number_var}\n    LIMIT 1 by val_id\n  ) AS current\nLEFT JOIN\n  (\n    SELECT val_balance, val_id, val_nos_id \n    FROM validators_summary \n    WHERE \n      val_status in ['active_ongoing', 'active_exiting', 'active_slashed', 'pending_initialized'] AND\n      CONCAT(toString(val_nos_module_id), ';', toString(val_nos_id))\n        IN arrayConcat(['${nos_global_index_var}'], splitByChar('|','${dvt_nos_global_indexes_var}')) AND\n      val_stuck = 0 AND\n      epoch = ${epoch_number_var} - 6\n    LIMIT 1 by val_id\n  ) AS previous\nON\n  previous.val_nos_id = current.val_nos_id AND \n  previous.val_id = current.val_id\nLEFT JOIN (\n  SELECT\n    sum(val_balance_withdrawn) as withdrawn, val_id, val_nos_id\n  FROM (\n    SELECT val_balance_withdrawn, val_id, val_nos_id\n    FROM validators_summary\n    WHERE\n      CONCAT(toString(val_nos_module_id), ';', toString(val_nos_id))\n        IN arrayConcat(['${nos_global_index_var}'], splitByChar('|','${dvt_nos_global_indexes_var}')) AND\n      val_stuck = 0 AND\n      epoch > (${epoch_number_var} - 6) AND epoch <= ${epoch_number_var}\n    LIMIT 1 BY epoch, val_id\n  )\n  GROUP BY val_id, val_nos_id\n) AS withdrawals\nON\n  withdrawals.val_nos_id = current.val_nos_id AND\n  withdrawals.val_id = current.val_id\nHAVING (current.val_balance - previous.val_balance + ifNull(withdrawals.withdrawn, 0)) < 0 and current.val_slashed = 0\nORDER BY GWei ASC, Validator\nLIMIT ${limit}",
     "rawQuery": "SELECT\n  if('2;0|2;1' != '', current.val_nos_name, NULL) as Operator,\n  current.val_balance - previous.val_balance + ifNull(withdrawals.withdrawn, 0) AS GWei,\n  current.val_id as Validator\nFROM \n  (\n    SELECT val_balance, val_id, val_nos_id, val_slashed, val_nos_name\n    FROM validators_summary \n    WHERE \n      val_status in ['active_ongoing', 'active_exiting', 'active_slashed', 'pending_initialized'] AND\n      CONCAT(toString(val_nos_module_id), ';', toString(val_nos_id))\n        IN arrayConcat(['1;0'], splitByChar('|','2;0|2;1')) AND\n      val_stuck = 0 AND\n      epoch = 222126\n    LIMIT 1 by val_id\n  ) AS current\nLEFT JOIN\n  (\n    SELECT val_balance, val_id, val_nos_id \n    FROM validators_summary \n    WHERE \n      val_status in ['active_ongoing', 'active_exiting', 'active_slashed', 'pending_initialized'] AND\n      CONCAT(toString(val_nos_module_id), ';', toString(val_nos_id))\n        IN arrayConcat(['1;0'], splitByChar('|','2;0|2;1')) AND\n      val_stuck = 0 AND\n      epoch = 222126 - 6\n    LIMIT 1 by val_id\n  ) AS previous\nON\n  previous.val_nos_id = current.val_nos_id AND \n  previous.val_id = current.val_id\nLEFT JOIN (\n  SELECT\n    sum(val_balance_withdrawn) as withdrawn, val_id, val_nos_id\n  FROM (\n    SELECT val_balance_withdrawn, val_id, val_nos_id\n    FROM validators_summary\n    WHERE\n      CONCAT(toString(val_nos_module_id), ';', toString(val_nos_id))\n        IN arrayConcat(['1;0'], splitByChar('|','2;0|2;1')) AND\n      val_stuck = 0 AND\n      epoch > (222126 - 6) AND epoch <= 222126\n    LIMIT 1 BY epoch, val_id\n  )\n  GROUP BY val_id, val_nos_id\n) AS withdrawals\nON\n  withdrawals.val_nos_id = current.val_nos_id AND\n  withdrawals.val_id = current.val_id\nHAVING (current.val_balance - previous.val_balance + ifNull(withdrawals.withdrawn, 0)) < 0 and current.val_slashed = 0\nORDER BY GWei ASC, Validator\nLIMIT 100",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Missed proposals",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 27 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n  if('${dvt_nos_global_indexes_var}' != '', val_nos_name, NULL) as Operator,\n  block_to_propose as Block,\n  val_id as Validator\nFROM validators_summary\nWHERE\n  CONCAT(toString(val_nos_module_id), ';', toString(val_nos_id))\n    IN arrayConcat(['${nos_global_index_var}'], splitByChar('|','${dvt_nos_global_indexes_var}')) AND\n  is_proposer = 1 AND\n  block_proposed = 0 AND\n  val_stuck = 0 AND\n  (epoch = ${epoch_number_var}) AND\n  val_nos_name = '${nos_name_var}'\nORDER BY block_to_propose DESC, val_id\nLIMIT 1 by val_id",
     "rawQuery": "SELECT\n  if('2;0|2;1' != '', val_nos_name, NULL) as Operator,\n  block_to_propose as Block,\n  val_id as Validator\nFROM validators_summary\nWHERE\n  CONCAT(toString(val_nos_module_id), ';', toString(val_nos_id))\n    IN arrayConcat(['1;0'], splitByChar('|','2;0|2;1')) AND\n  is_proposer = 1 AND\n  block_proposed = 0 AND\n  val_stuck = 0 AND\n  (epoch = 222135) AND\n  val_nos_name = 'Operator_1'\nORDER BY block_to_propose DESC, val_id\nLIMIT 1 by val_id",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Bad Sync participation (${sync_epochs_var} epochs in a row)",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 27 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n  if('${dvt_nos_global_indexes_var}' != '', val_nos_name, NULL) as Operator,\n  val_id as Validator\nFROM (\n  SELECT\n    val_id,\n    val_nos_name,\n    count() AS count_fail\n  FROM (\n    SELECT val_id, val_nos_name\n    FROM validators_summary\n    WHERE\n      CONCAT(toString(val_nos_module_id), ';', toString(val_nos_id))\n        IN arrayConcat(['${nos_global_index_var}'], splitByChar('|','${dvt_nos_global_indexes_var}')) AND\n      is_sync = 1 AND \n      val_stuck = 0 AND \n      sync_percent < (${chain_sync_avg_participation} - ${sync_participation_distance_var}) AND\n      (epoch <= ${epoch_number_var} AND epoch > (${epoch_number_var} - ${sync_epochs_var}))\n    LIMIT 1 by epoch, val_id  \n  )\n  GROUP BY val_id, val_nos_name\n)\nWHERE count_fail = ${sync_epochs_var}\nORDER BY count_fail DESC, val_id",
     "rawQuery": "SELECT\n  if('2;0|2;1' != '', val_nos_name, NULL) as Operator,\n  val_id as Validator\nFROM (\n  SELECT\n    val_id,\n    val_nos_name,\n    count() AS count_fail\n  FROM (\n    SELECT val_id, val_nos_name\n    FROM validators_summary\n    WHERE\n      CONCAT(toString(val_nos_module_id), ';', toString(val_nos_id))\n        IN arrayConcat(['1;0'], splitByChar('|','2;0|2;1')) AND\n      is_sync = 1 AND \n      val_stuck = 0 AND \n      sync_percent < (99.200439453125 - 0) AND\n      (epoch <= 222137 AND epoch > (222137 - 3))\n    LIMIT 1 by epoch, val_id  \n  )\n  GROUP BY val_id, val_nos_name\n)\nWHERE count_fail = 3\nORDER BY count_fail DESC, val_id",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Missed attestation (${att_epochs_var} epochs in a row)",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 35 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "\nSELECT\n  if('${dvt_nos_global_indexes_var}' != '', val_nos_name, NULL) as Operator,\n  val_id as Validator\nFROM (\n    SELECT\n      val_id,\n      val_nos_name,\n      count() as count_fail\n    FROM (\n      SELECT val_id, val_nos_name\n      FROM validators_summary\n      WHERE \n        att_happened = 0 AND\n        val_stuck = 0 AND\n        CONCAT(toString(val_nos_module_id), ';', toString(val_nos_id))\n          IN arrayConcat(['${nos_global_index_var}'], splitByChar('|','${dvt_nos_global_indexes_var}')) AND\n        (epoch <= ${epoch_number_var} AND epoch > (${epoch_number_var} - ${att_epochs_var}))\n      LIMIT 1 by epoch, val_id\n    )\n    GROUP BY val_id, val_nos_name\n)\nWHERE count_fail = ${att_epochs_var}\nORDER BY count_fail DESC, val_id\nLIMIT ${limit}",
     "rawQuery": "SELECT\n  if('2;0|2;1' != '', val_nos_name, NULL) as Operator,\n  val_id as Validator\nFROM (\n    SELECT\n      val_id,\n      val_nos_name,\n      count() as count_fail\n    FROM (\n      SELECT val_id, val_nos_name\n      FROM validators_summary\n      WHERE \n        att_happened = 0 AND\n        val_stuck = 0 AND\n        CONCAT(toString(val_nos_module_id), ';', toString(val_nos_id))\n          IN arrayConcat(['1;0'], splitByChar('|','2;0|2;1')) AND\n        (epoch <= 222140 AND epoch > (222140 - 3))\n      LIMIT 1 by epoch, val_id\n    )\n    GROUP BY val_id, val_nos_name\n)\nWHERE count_fail = 3\nORDER BY count_fail DESC, val_id\nLIMIT 100",
     "round": "0s"
    }
   ]
  },
  {
   "title": "High inclusion delay (${att_epochs_var} epochs in a row)",
   "type": "table",
   "description": "inc. delay > 1",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 35 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n  if('${dvt_nos_global_indexes_var}' != '', val_nos_name, NULL) as Operator,\n  val_id as Validator,\n  count() as count_fail\nFROM (\n  SELECT val_id, val_nos_name\n  FROM validators_summary\n  WHERE\n    CONCAT(toString(val_nos_module_id), ';', toString(val_nos_id))\n      IN arrayConcat(['${nos_global_index_var}'], splitByChar('|','${dvt_nos_global_indexes_var}')) AND\n    att_happened = 1 AND\n    att_inc_delay > 1 AND\n    val_stuck = 0 AND\n    (epoch <= ${epoch_number_var} AND epoch > (${epoch_number_var} - ${att_epochs_var}))\n  LIMIT 1 by epoch, val_id\n)\nGROUP BY val_id, val_nos_name\nHAVING count_fail = ${att_epochs_var}\nORDER BY count_fail DESC, val_id\nLIMIT ${limit}",
     "rawQuery": "SELECT\n  if('2;0|2;1' != '', val_nos_name, NULL) as Operator,\n  val_id as Validator,\n  count() as count_fail\nFROM (\n  SELECT val_id, val_nos_name\n  FROM validators_summary\n  WHERE\n    CONCAT(toString(val_nos_module_id), ';', toString(val_nos_id))\n      IN arrayConcat(['1;0'], splitByChar('|','2;0|2;1')) AND\n    att_happened = 1 AND\n    att_inc_delay > 1 AND\n    val_stuck = 0 AND\n    (epoch <= 222142 AND epoch > (222142 - 3))\n  LIMIT 1 by epoch, val_id\n)\nGROUP BY val_id, val_nos_name\nHAVING count_fail = 3\nORDER BY count_fail DESC, val_id\nLIMIT 100",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Invalid attestation properties (${att_epochs_var} epochs in a row)",
   "type": "table",
   "description": "head or target or source",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 35 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n  if('${dvt_nos_global_indexes_var}' != '', val_nos_name, NULL) as Operator,\n  val_id as Validator,\n  count() as count_fail\nFROM (\n  SELECT val_id, val_nos_name\n  FROM validators_summary\n  WHERE\n    CONCAT(toString(val_nos_module_id), ';', toString(val_nos_id))\n      IN arrayConcat(['${nos_global_index_var}'], splitByChar('|','${dvt_nos_global_indexes_var}')) AND\n    (att_valid_head + att_valid_target + att_valid_source = 1) AND\n    val_stuck = 0 AND\n    (epoch <= ${epoch_number_var} AND epoch > (${epoch_number_var} - ${att_epochs_var}))\n  LIMIT 1 by epoch, val_id\n)\nGROUP BY val_id, val_nos_name\nHAVING count_fail = ${att_epochs_var}\nORDER BY count_fail DESC, val_id\nLIMIT ${limit}",
     "rawQuery": "SELECT\n  if('2;0|2;1' != '', val_nos_name, NULL) as Operator,\n  val_id as Validator,\n  count() as count_fail\nFROM (\n  SELECT val_id, val_nos_name\n  FROM validators_summary\n  WHERE\n    CONCAT(toString(val_nos_module_id), ';', toString(val_nos_id))\n      IN arrayConcat(['1;0'], splitByChar('|','2;0|2;1')) AND\n    (att_valid_head + att_valid_target + att_valid_source = 1) AND\n    val_stuck = 0 AND\n    (epoch <= 222147 AND epoch > (222147 - 3))\n  LIMIT 1 by epoch, val_id\n)\nGROUP BY val_id, val_nos_name\nHAVING count_fail = 3\nORDER BY count_fail DESC, val_id\nLIMIT 100",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Slashed",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 43 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    if('${dvt_nos_global_indexes_var}' != '', val_nos_name, NULL) as Operator,\n    val_status as Status,\n    val_id as Validator\nFROM validators_summary\nWHERE\n  (val_status == 'active_slashed' OR val_status == 'exited_slashed' OR val_slashed == 1) AND\n  CONCAT(toString(val_nos_module_id), ';', toString(val_nos_id))\n    IN arrayConcat(['${nos_global_index_var}'], splitByChar('|','${dvt_nos_global_indexes_var}')) AND\n  epoch = ${epoch_number_var}\nORDER BY val_id\nLIMIT 1 by val_id",
     "rawQuery": "SELECT\n    if('2;0|2;1' != '', val_nos_name, NULL) as Operator,\n    val_status as Status,\n    val_id as Validator\nFROM validators_summary\nWHERE\n  (val_status == 'active_slashed' OR val_status == 'exited_slashed' OR val_slashed == 1) AND\n  CONCAT(toString(val_nos_module_id), ';', toString(val_nos_id))\n    IN arrayConcat(['1;0'], splitByChar('|','2;0|2;1')) AND\n  epoch = 222149\nORDER BY val_id\nLIMIT 1 by val_id",
     "round": "0s"
    }
   ]
  },
  {
   "title": "💸 Balances",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "panels": [
    {
     "title": "Operator balance 24h delta",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "(sum by (nos_name) (catalist_validators_monitoring_operator_balance_24h_difference{nos_name=~\"${mapped_nos_names_var}\"}) / 10 ^ 9) AND ON() changes(catalist_validators_monitoring_epoch_number[$__rate_interval]) > 0",
       "legendFormat": "{{nos_name}} delta"
      }
     ]
    },
    {
     "title": "Avg validator balances delta",
     "type": "timeseries",
     "description": "Delta: current slot - 192 slot",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 81 },
     "fieldConfig": { "defaults": { "unit": "GWei" } },
     "targets": [
      {
       "expr": "sum by (nos_name) (catalist_validators_monitoring_validator_balances_delta{nos_name=~\"${mapped_nos_names_var}\"}) AND ON() changes(catalist_validators_monitoring_epoch_number[$__rate_interval]) > 0",
       "legendFormat": "{{nos_name}} delta"
      }
     ]
    },
    {
     "title": "Worst validator balances delta [0.1% percentile]",
     "type": "timeseries",
     "description": "Delta: current slot - 192 slot",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 81 },
     "fieldConfig": { "defaults": { "unit": "GWei" } },
     "targets": [
      {
       "expr": "sum by (nos_name) (catalist_validators_monitoring_validator_quantile_001_balances_delta{nos_name=~\"${mapped_nos_names_var}\"}) AND ON() changes(catalist_validators_monitoring_epoch_number[$__rate_interval]) > 0",
       "legendFormat": "{{nos_name}} delta"
      }
     ]
    },
    {
     "title": "Validators with worst balance delta",
     "type": "table",
     "description": "Delta: current slot - 192 slot",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 87 },
     "targets": [
      {
       "dateTimeType": "DATETIME",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "SELECT\n  if('${dvt_nos_global_indexes_var}' != '', current.val_nos_name, NULL) as Operator,\n  current.val_balance - previous.val_balance + ifNull(withdrawals.withdrawn, 0) AS GWei,\n  current.val_id as Validator\nFROM \n  (\n    SELECT val_balance, val_id, val_nos_id, val_nos_name \n    FROM validators_summary \n    WHERE \n      val_status in ['active_ongoing', 'active_exiting', 'active_slashed', 'pending_initialized'] AND\n      val_nos_id IS NOT NULL AND\n      val_stuck = 0 AND\n      epoch = ${epoch_number_var} AND\n      CONCAT(toString(val_nos_module_id), ';', toString(val_nos_id))\n        IN arrayConcat(['${nos_global_index_var}'], splitByChar('|','${dvt_nos_global_indexes_var}'))\n    LIMIT 1 by val_id\n  ) AS current\nLEFT JOIN\n  (\n    SELECT val_balance, val_id, val_nos_id \n    FROM validators_summary \n    WHERE \n      val_status in ['active_ongoing', 'active_exiting', 'active_slashed', 'pending_initialized'] AND \n      val_nos_id IS NOT NULL AND\n      val_stuck = 0 AND\n      epoch = ${epoch_number_var} - 6 AND\n      CONCAT(toString(val_nos_module_id), ';', toString(val_nos_id))\n        IN arrayConcat(['${nos_global_index_var}'], splitByChar('|','${dvt_nos_global_indexes_var}'))\n    LIMIT 1 by val_id\n  ) AS previous\nON\n  previous.val_nos_id = current.val_nos_id AND \n  previous.val_id = current.val_id\nLEFT JOIN (\n  SELECT\n    sum(val_balance_withdrawn) as withdrawn, val_id, val_nos_id\n  FROM (\n    SELECT val_balance_withdrawn, val_id, val_nos_id\n    FROM validators_summary\n    WHERE\n      val_nos_id IS NOT NULL AND\n      val_status in ['active_ongoing', 'active_exiting', 'active_slashed', 'pending_initialized'] AND\n      val_stuck = 0 AND\n      epoch > (${epoch_number_var} - 6) AND epoch <= ${epoch_number_var} AND\n      CONCAT(toString(val_nos_module_id), ';', toString(val_nos_id))\n        IN arrayConcat(['${nos_global_index_var}'], splitByChar('|','${dvt_nos_global_indexes_var}'))\n    LIMIT 1 BY epoch, val_id\n  )\n  GROUP BY val_id, val_nos_id\n) AS withdrawals\nON\n  withdrawals.val_nos_id = current.val_nos_id AND\n  withdrawals.val_id = current.val_id\nORDER BY GWei ASC, Validator\nLIMIT 100",
       "rawQuery": "SELECT\n  if('2;0|2;1' != '', current.val_nos_name, NULL) as Operator,\n  current.val_balance - previous.val_balance + ifNull(withdrawals.withdrawn, 0) AS GWei,\n  current.val_id as Validator\nFROM \n  (\n    SELECT val_balance, val_id, val_nos_id, val_nos_name \n    FROM validators_summary \n    WHERE \n      val_status in ['active_ongoing', 'active_exiting', 'active_slashed', 'pending_initialized'] AND\n      val_nos_id IS NOT NULL AND\n      val_stuck = 0 AND\n      epoch = 222150 AND\n      CONCAT(toString(val_nos_module_id), ';', toString(val_nos_id))\n        IN arrayConcat(['1;0'], splitByChar('|','2;0|2;1'))\n    LIMIT 1 by val_id\n  ) AS current\nLEFT JOIN\n  (\n    SELECT val_balance, val_id, val_nos_id \n    FROM validators_summary \n    WHERE \n      val_status in ['active_ongoing', 'active_exiting', 'active_slashed', 'pending_initialized'] AND \n      val_nos_id IS NOT NULL AND\n      val_stuck = 0 AND\n      epoch = 222150 - 6 AND\n      CONCAT(toString(val_nos_module_id), ';', toString(val_nos_id))\n        IN arrayConcat(['1;0'], splitByChar('|','2;0|2;1'))\n    LIMIT 1 by val_id\n  ) AS previous\nON\n  previous.val_nos_id = current.val_nos_id AND \n  previous.val_id = current.val_id\nLEFT JOIN (\n  SELECT\n    sum(val_balance_withdrawn) as withdrawn, val_id, val_nos_id\n  FROM (\n    SELECT val_balance_withdrawn, val_id, val_nos_id\n    FROM validators_summary\n    WHERE\n      val_nos_id IS NOT NULL AND\n      val_status in ['active_ongoing', 'active_exiting', 'active_slashed', 'pending_initialized'] AND\n      val_stuck = 0 AND\n      epoch > (222150 - 6) AND epoch <= 222150 AND\n      CONCAT(toString(val_nos_module_id), ';', toString(val_nos_id))\n        IN arrayConcat(['1;0'], splitByChar('|','2;0|2;1'))\n    LIMIT 1 BY epoch, val_id\n  )\n  GROUP BY val_id, val_nos_id\n) AS withdrawals\nON\n  withdrawals.val_nos_id = current.val_nos_id AND\n  withdrawals.val_id = current.val_id\nORDER BY GWei ASC, Validator\nLIMIT 100",
       "round": "0s"
      }
     ]
    },
    {
     "title": "Number of validators with negative delta",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 16, "x": 8, "y": 87 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (nos_name) (catalist_validators_monitoring_validator_count_with_negative_balances_delta{nos_name=~\"${mapped_nos_names_var}\"}) AND ON() changes(catalist_validators_monitoring_epoch_number[$__rate_interval]) > 0",
       "legendFormat": "{{nos_name}} delta"
      }
     ]
    }
   ]
  },
  {
   "title": "📥 Proposals",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "collapsed": true,
   "panels": [
    {
     "title": "Missed proposals (${epochs_range} epochs range)",
     "type": "table",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 77 },
     "targets": [
      {
       "dateTimeType": "DATETIME",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "SELECT\n  if('${dvt_nos_global_indexes_var}' != '', val_nos_name, NULL) as Operator,\n  block_to_propose as Block,\n  val_id as Validator\nFROM validators_summary\nWHERE\n  CONCAT(toString(val_nos_module_id), ';', toString(val_nos_id))\n    IN arrayConcat(['${nos_global_index_var}'], splitByChar('|','${dvt_nos_global_indexes_var}')) AND\n  is_proposer = 1 AND\n  block_proposed = 0 AND\n  (epoch <= ${epoch_number_var} AND epoch > (${epoch_number_var} - ${epochs_range}))\nORDER BY block_to_propose DESC, val_id\nLIMIT 1 by epoch, val_id",
       "rawQuery": "SELECT\n  if('2;0|2;1' != '', val_nos_name, NULL) as Operator,\n  block_to_propose as Block,\n  val_id as Validator\nFROM validators_summary\nWHERE\n  CONCAT(toString(val_nos_module_id), ';', toString(val_nos_id))\n    IN arrayConcat(['1;0'], splitByChar('|','2;0|2;1')) AND\n  is_proposer = 1 AND\n  block_proposed = 0 AND\n  (epoch <= 222157 AND epoch > (222157 - 19))\nORDER BY block_to_propose DESC, val_id\nLIMIT 1 by epoch, val_id",
       "round": "0s"
      }
     ]
    },
    {
     "title": "Number of validators with missed proposals",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 16, "x": 8, "y": 77 },
     "targets": [
      {
       "expr": "sum by (nos_name) (catalist_validators_monitoring_validator_count_miss_propose{nos_name=~'${mapped_nos_names_var}'}) AND ON() changes(catalist_validators_monitoring_epoch_number[$__rate_interval]) > 0",
       "legendFormat": "{{nos_name}} delta"
      }
     ]
    }
   ]
  },
  {
   "title": "🔄 Sync Committee participation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "collapsed": true,
   "panels": [
    {
     "title": "${nos_name_var} vs Other",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 78 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "sum(catalist_validators_monitoring_other_sync_participation_avg_percent) AND ON() changes(catalist_validators_monitoring_epoch_number[$__rate_interval]) > 0",
       "legendFormat": "Rest of chain"
      },
      {
       "expr": "avg(catalist_validators_monitoring_operator_sync_participation_avg_percent{nos_name!~'${mapped_nos_names_var}'} AND ON(nos_name) (catalist_validators_monitoring_validator_count_with_good_sync_participation{nos_name!~'${mapped_nos_names_var}'} + catalist_validators_monitoring_validator_count_with_sync_participation_less_avg{nos_name!~'${mapped_nos_names_var}'} > 0) AND ON() changes(catalist_validators_monitoring_epoch_number[25s]) > 0) ",
       "legendFormat": "Rest of User's"
      },
      {
       "expr": "sum by (nos_name) (catalist_validators_monitoring_operator_sync_participation_avg_percent{nos_name=~'${mapped_nos_names_var}'}) AND ON(nos_name) (catalist_validators_monitoring_validator_count_with_good_sync_participation{nos_name=~'${mapped_nos_names_var}'} + catalist_validators_monitoring_validator_count_with_sync_participation_less_avg{nos_name=~'${mapped_nos_names_var}'} > 0) AND ON() changes(catalist_validators_monitoring_epoch_number[25s]) > 0",
       "legendFormat": "{{nos_name}}"
      }
     ]
    },
    {
     "title": "Bad Sync Committee participation",
     "type": "table",
     "description": "AVG.\n`Bad` is considered when validator's sync is less than chain avg value (including `SYNC_PARTICIPATION_DISTANCE_DOWN_FROM_CHAIN_AVG`) ",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 84 },
     "targets": [
      {
       "dateTimeType": "DATETIME",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "SELECT\n    if('${dvt_nos_global_indexes_var}' != '', val_nos_name, NULL) as Operator,\n    sync_percent as Percent,\n    val_id as Validator\nFROM\n    validators_summary\nWHERE\n    CONCAT(toString(val_nos_module_id), ';', toString(val_nos_id))\n      IN arrayConcat(['${nos_global_index_var}'], splitByChar('|','${dvt_nos_global_indexes_var}')) AND\n    val_stuck = 0 AND\n    epoch = ${epoch_number_var} AND\n    is_sync = 1 AND\n    sync_percent < (${chain_sync_avg_participation} - ${sync_participation_distance_var})\nORDER BY sync_percent, val_id\nLIMIT 1 by val_id",
       "rawQuery": "SELECT\n    if('2;0|2;1' != '', val_nos_name, NULL) as Operator,\n    sync_percent as Percent,\n    val_id as Validator\nFROM\n    validators_summary\nWHERE\n    CONCAT(toString(val_nos_module_id), ';', toString(val_nos_id))\n      IN arrayConcat(['1;0'], splitByChar('|','2;0|2;1')) AND\n    val_stuck = 0 AND\n    epoch = 222160 AND\n    is_sync = 1 AND\n    sync_percent < (99.0234375 - 0)\nORDER BY sync_percent, val_id\nLIMIT 1 by val_id",
       "round": "0s"
      }
     ]
    },
    {
     "title": "Number of validators with sync participation less average",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 16, "x": 8, "y": 84 },
     "targets": [
      {
       "expr": "sum by (nos_name) (catalist_validators_monitoring_validator_count_with_sync_participation_less_avg{nos_name=~'${mapped_nos_names_var}'}) AND ON() changes(catalist_validators_monitoring_epoch_number[$__rate_interval]) > 0",
       "legendFormat": "{{nos_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "📝 Attestations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "collapsed": true,
   "panels": [
    {
     "title": "Validators with MISSED attestation",
     "type": "table",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 79 },
     "targets": [
      {
       "dateTimeType": "DATETIME",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "    SELECT\n      if('${dvt_nos_global_indexes_var}' != '', val_nos_name, NULL) as Operator,\n      val_id as Validator\n    FROM validators_summary\n    WHERE\n      att_happened = 0 AND\n      CONCAT(toString(val_nos_module_id), ';', toString(val_nos_id))\n        IN arrayConcat(['${nos_global_index_var}'], splitByChar('|','${dvt_nos_global_indexes_var}')) AND\n      val_stuck = 0 AND epoch = ${epoch_number_var}\n    ORDER BY val_id\n    LIMIT 1 by val_id\n    LIMIT ${limit}",
       "rawQuery": "SELECT\n      if('2;0|2;1' != '', val_nos_name, NULL) as Operator,\n      val_id as Validator\n    FROM validators_summary\n    WHERE\n      att_happened = 0 AND\n      CONCAT(toString(val_nos_module_id), ';', toString(val_nos_id))\n        IN arrayConcat(['1;0'], splitByChar('|','2;0|2;1')) AND\n      val_stuck = 0 AND epoch = 222164\n    ORDER BY val_id\n    LIMIT 1 by val_id\n    LIMIT 100",
       "round": "0s"
      }
     ]
    },
    {
     "title": "Number of validators with MISSED attestation",
     "type": "timeseries",
     "description": "User only",
     "gridPos": { "h": 8, "w": 16, "x": 8, "y": 79 },
     "targets": [
      {
       "expr": "sum by (nos_name) (catalist_validators_monitoring_validator_count_miss_attestation{nos_name=~'${mapped_nos_names_var}'}) AND ON() changes(catalist_validators_monitoring_epoch_number[$__rate_interval]) > 0",
       "legendFormat": "{{nos_name}}"
      }
     ]
    },
    {
     "title": "Validators with high INC. DELAY attestation",
     "type": "table",
     "description": "inc. delay > 1",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 87 },
     "targets": [
      {
       "dateTimeType": "DATETIME",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "\n    SELECT\n      if('${dvt_nos_global_indexes_var}' != '', val_nos_name, NULL) as Operator,\n      val_id as Validator\n    FROM validators_summary\n    WHERE\n      att_happened = 1 AND\n      att_inc_delay > 1 AND\n      CONCAT(toString(val_nos_module_id), ';', toString(val_nos_id))\n        IN arrayConcat(['${nos_global_index_var}'], splitByChar('|','${dvt_nos_global_indexes_var}')) AND\n      val_stuck = 0 AND\n      epoch = ${epoch_number_var}\n    ORDER BY val_id\n    LIMIT 1 by val_id\n    LIMIT ${limit}",
       "rawQuery": "SELECT\n      if('2;0|2;1' != '', val_nos_name, NULL) as Operator,\n      val_id as Validator\n    FROM validators_summary\n    WHERE\n      att_happened = 1 AND\n      att_inc_delay > 1 AND\n      CONCAT(toString(val_nos_module_id), ';', toString(val_nos_id))\n        IN arrayConcat(['1;0'], splitByChar('|','2;0|2;1')) AND\n      val_stuck = 0 AND\n      epoch = 222165\n    ORDER BY val_id\n    LIMIT 1 by val_id\n    LIMIT 100",
       "round": "0s"
      }
     ]
    },
    {
     "title": "Number of validators with high attestation INC. DELAY",
     "type": "timeseries",
     "description": "User only",
     "gridPos": { "h": 8, "w": 16, "x": 8, "y": 87 },
     "targets": [
      {
       "expr": "sum by (nos_name) (catalist_validators_monitoring_validator_count_invalid_attestation{nos_name=~'${mapped_nos_names_var}', reason=\"high_inclusion_delay\"}) AND ON() changes(catalist_validators_monitoring_epoch_number[$__rate_interval]) > 0",
       "legendFormat": "{{nos_name}}"
      }
     ]
    },
    {
     "title": "Validators with invalid HEAD",
     "type": "table",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 95 },
     "targets": [
      {
       "dateTimeType": "DATETIME",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "\n    SELECT\n      if('${dvt_nos_global_indexes_var}' != '', val_nos_name, NULL) as Operator,\n      val_id as Validator\n    FROM validators_summary\n    WHERE\n      att_valid_head = 0 AND\n      CONCAT(toString(val_nos_module_id), ';', toString(val_nos_id))\n        IN arrayConcat(['${nos_global_index_var}'], splitByChar('|','${dvt_nos_global_indexes_var}')) AND\n      val_stuck = 0 AND\n      epoch = ${epoch_number_var}\n    ORDER BY val_id\n    LIMIT 1 BY val_id\n    LIMIT ${limit}",
       "rawQuery": "SELECT\n      if('2;0|2;1' != '', val_nos_name, NULL) as Operator,\n      val_id as Validator\n    FROM validators_summary\n    WHERE\n      att_valid_head = 0 AND\n      CONCAT(toString(val_nos_module_id), ';', toString(val_nos_id))\n        IN arrayConcat(['1;0'], splitByChar('|','2;0|2;1')) AND\n      val_stuck = 0 AND\n      epoch = 222169\n    ORDER BY val_id\n    LIMIT 1 BY val_id\n    LIMIT 100",
       "round": "0s"
      }
     ]
    },
    {
     "title": "Number of validators with invalid attestation HEAD",
     "type": "timeseries",
     "description": "User only",
     "gridPos": { "h": 8, "w": 16, "x": 8, "y": 95 },
     "targets": [
      {
       "expr": "sum by (nos_name) (catalist_validators_monitoring_validator_count_invalid_attestation{nos_name=~'${mapped_nos_names_var}', reason=\"invalid_head\"}) AND ON() changes(catalist_validators_monitoring_epoch_number[$__rate_interval]) > 0",
       "legendFormat": "{{nos_name}}"
      }
     ]
    },
    {
     "title": "Validators with invalid TARGET",
     "type": "table",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 103 },
     "targets": [
      {
       "dateTimeType": "DATETIME",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "\n    SELECT\n      if('${dvt_nos_global_indexes_var}' != '', val_nos_name, NULL) as Operator,\n      val_id as Validator\n    FROM validators_summary\n    WHERE\n      att_valid_target = 0 AND\n      CONCAT(toString(val_nos_module_id), ';', toString(val_nos_id))\n        IN arrayConcat(['${nos_global_index_var}'], splitByChar('|','${dvt_nos_global_indexes_var}')) AND\n      val_stuck = 0 AND\n      epoch = ${epoch_number_var}\n    ORDER BY val_id\n    LIMIT 1 by val_id\n    LIMIT ${limit}",
       "rawQuery": "SELECT\n      if('2;0|2;1' != '', val_nos_name, NULL) as Operator,\n      val_id as Validator\n    FROM validators_summary\n    WHERE\n      att_valid_target = 0 AND\n      CONCAT(toString(val_nos_module_id), ';', toString(val_nos_id))\n        IN arrayConcat(['1;0'], splitByChar('|','2;0|2;1')) AND\n      val_stuck = 0 AND\n      epoch = 222158\n    ORDER BY val_id\n    LIMIT 1 by val_id\n    LIMIT 100",
       "round": "0s"
      }
     ]
    },
    {
     "title": "Number of validators with invalid attestation TARGET",
     "type": "timeseries",
     "description": "User only",
     "gridPos": { "h": 8, "w": 16, "x": 8, "y": 103 },
     "targets": [
      {
       "expr": "sum by (nos_name) (catalist_validators_monitoring_validator_count_invalid_attestation{nos_name=~'${mapped_nos_names_var}', reason=\"invalid_target\"}) AND ON() changes(catalist_validators_monitoring_epoch_number[$__rate_interval]) > 0",
       "legendFormat": "{{nos_name}}"
      }
     ]
    },
    {
     "title": "Validator with invalid SOURCE",
     "type": "table",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 111 },
     "targets": [
      {
       "dateTimeType": "DATETIME",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "\n    SELECT\n      if('${dvt_nos_global_indexes_var}' != '', val_nos_name, NULL) as Operator,\n      val_id as Validator\n    FROM validators_summary\n    WHERE\n      att_valid_source = 0 AND\n      CONCAT(toString(val_nos_module_id), ';', toString(val_nos_id))\n        IN arrayConcat(['${nos_global_index_var}'], splitByChar('|','${dvt_nos_global_indexes_var}')) AND\n      val_stuck = 0 AND epoch = ${epoch_number_var}\n    ORDER BY val_id\n    LIMIT 1 by val_id\n    LIMIT ${limit}",
       "rawQuery": "SELECT\n      if('2;0|2;1' != '', val_nos_name, NULL) as Operator,\n      val_id as Validator\n    FROM validators_summary\n    WHERE\n      att_valid_source = 0 AND\n      CONCAT(toString(val_nos_module_id), ';', toString(val_nos_id))\n        IN arrayConcat(['1;0'], splitByChar('|','2;0|2;1')) AND\n      val_stuck = 0 AND epoch = 222171\n    ORDER BY val_id\n    LIMIT 1 by val_id\n    LIMIT 100",
       "round": "0s"
      }
     ]
    },
    {
     "title": "Number of validators with invalid attestation SOURCE",
     "type": "timeseries",
     "description": "User only",
     "gridPos": { "h": 8, "w": 16, "x": 8, "y": 111 },
     "targets": [
      {
       "expr": "sum by (nos_name) (catalist_validators_monitoring_validator_count_invalid_attestation{nos_name=~'${mapped_nos_names_var}', reason=\"invalid_source\"}) AND ON() changes(catalist_validators_monitoring_epoch_number[$__rate_interval]) > 0",
       "legendFormat": "{{nos_name}}"
      }
     ]
    }
   ]
  }
 ]
}