global:
  scrape_interval: 10s
  evaluation_interval: 15s
  external_labels:
    monitor: 'my-project'

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - 'operators_map.yml'
  - 'alerts_rules.yml'

scrape_configs:
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'prometheus'
    metrics_path: /metrics
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'catalist_validators_monitoring'
    static_configs:
      - targets: ['app:8080']
    metrics_path: /metrics
    metric_relabel_configs:
      - source_labels: [nos_module_id, nos_id]
        regex: '(\d+);(\d+)'
        replacement: ${1};${2}
        target_label: nos_global_index

  - job_name: 'keys_api'
    metrics_path: /metrics
    static_configs:
      - targets: ['kapi.catalist.app']
